### ISSUE TITLE
Script fails if file "/etc/setup/setup.sh" already exists, and this is not file created by this script

### ISSUE THREAD

**Issue by Prince-Mandor** [cup/sage#39]
OK, I found cause of previous issue.
Script fails if file "/etc/setup/setup.sh" already exists, and this is not file created by this script.
Name "setup.sh" is really common, and another package already use it.

BTW, this also means, if setup.rc will be changed (by running setup directly, for example), this changes will not be monitored.

Possibly it will be better to create some temporary file with each run?

**Comment by cup** [comment]
you make a good point - but current no cygwin package creates this file

http://cygwin.com/cgi-bin2/package-grep.cgi?text=1&arch=x86_64&grep=setup/setup.sh

unless via some postinstall script - which means you created it with some homebrew thing.

if you can demonstrate a cygwin package that provides `/etc/setup/setup.sh` - then i will consider changing it

otherwise you can send a pull request and i will consider it - closing this until then - cheers

**Comment by Prince-Mandor** [comment]
As you like.
So far there are numerous attempts to create package manager for cygwin. with dosens of forks. So it is one of them obviously. 
Yes, they are all "homebrew thing" without clear installation instructions, and they putting their temporary files in random places. Do you really think it is good practice?

**Comment by cup** [comment]
I know its not a good practice. in fact it did used to be a temp file:

https://github.com/cup/sage/commit/a0dcfaf9ea911c3cb3c0670bf603f1b0b6e47743

but i changed it because i didnt like it filling up my temp folder

the real plan is to rewrite sage with a proper programming language:

http://github.com/cup/sage/issues/21

perhap rust or Go - but i am deciding what language to use before that happens

http://github.com/cup/cup.github.io/tree/master/rosetta

once the rewrite is done:

- velour wont be needed anymore
- even Dash wont be needed
- temp files will be reduced or eliminated

so you can understand why i might not been keen on fixing issues with the shell
script.
